- type: job
  id: SeniorLogistician
  name: ведущий логист
  description: job-description-cargotech
  playTimeTracker: JobSeniorLogistician
  weight: 9
  startingGear: SeniorLogisticianGear
  icon: "JobIconSeniorLogistician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: SeniorLogisticianGear
  equipment:
    id: SeniorCourierPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff