- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
<<<<<<< HEAD
  
=======
  - Snowball
>>>>>>> aad5613341df4bd34b24db1b4c5a99a411f92cb6
