- type: playTimeTracker
  id: JobBlueshield

- type: playTimeTracker
  id: JobNanotrasenRepresentive

- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobPathologist

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobJurist

- type: playTimeTracker
  id: JobCargoMailman

- type: playTimeTracker
  id: JobCargoAssistant

- type: playTimeTracker
  id: JobSeniorLogistician

- type: playTimeTracker
  id: JobSeniorServicer

# Ведущие роли отделов # Corvax Mentor Roles

#- type: playTimeTracker
#  id: JobSeniorOfficer

#- type: playTimeTracker
#  id: JobSeniorEngineer

#- type: playTimeTracker
#  id: JobSeniorPhysician

#- type: playTimeTracker
#  id: JobSeniorResearcher
