- type: job
  id: MedicalPathologist
  name: коронер
  description: Врач, которые относит трупы в морг и занимается прижизненной и посмертной диагностикой трупа. 
  playTimeTracker: JobMedicalPathologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs # Corvax-RoleTime
  weight: 5
  startingGear: PathologistGear
  icon: "JobIconPathologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Patologoanatom
  
- type: startingGear
  id: PathologistGear
  equipment:
    id: PathologistPDA
    ears: ClothingHeadsetPatologoanatom
    belt: ClothingBeltMedicalFilled
